### ISSUE TITLE
recaptcha not showing up

### ISSUE THREAD

**Issue by guaka** [vedmaka/Mediawiki-reCaptcha#3]
The extension is showing up at `Special:Version` but not at `index.php?title=Special:UserLogin&type=signup`

Not yet sure why.

**Comment by guaka** [comment]
I do spot `<script src='https://www.google.com/recaptcha/api.js'></script>` in the source.

But nothing like `<div class="g-recaptcha" data-sitekey="key"></div>` yet.

**Comment by vedmaka** [comment]
Can you please provide your MW version?

**Comment by guaka** [comment]
Was MW 1.20 or something, just upgraded to 1.24.1, still the same.

Does it suffice to require reCaptcha.php or does it also need ConfirmEdit or something else in some way?

**Comment by guaka** [comment]
Ah checked that. Fixed now! Still had some old Asirra code lying around.

Thanks!
